import Head from "next/head";
import Input123 from "./components/form/Input123";
import Footer from "./components/layout/Footer";
import Home from "./Home";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Home />
    </div>
  );
}
